name: Save new site

on:
  workflow_dispatch:
    inputs:
      json:
        description: "Site JSON"
        required: true
        type: string

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Save JSON
        run: |
          echo '${{ inputs.json }}' > site.json

      - name: Commit
        run: |
          git config user.name "paraspots-bot"
          git config user.email "bot@paraspots.at"
          git add site.json
          git commit -m "Add new site"
          git push
